const june2019roster = [
    'Aly S',
    'Anthony A',
    'Daniel A',
    'David W',
    'Drew P',
    'Elias R',
    'Emily C',
    'Emily R',
    'Ibrahim Y',
    'Jason M',
    'Jeremy M',
    'John D',
    'Johnny M',
    'Julia C',
    'Keith N',
    'Kenneth P',
    'Maria S',
    'Markus M',
    'Michael H',
    'Michael N',
    'Nathaniel C',
    'Nik A',
    'Peter R',
]

export default june2019roster;